---
title: "Forecast Evaluation"
author: "Lauren White (lauren.white@cdph.ca.gov)"
date: '2024-12-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(data.table)
library(tidyr)
library(scoringutils)
library(arrow)

season22_start_MMWR<- as.Date("2022-10-02")  #Beginning of week 40 for 2022-2023 season
season23_start_MMWR<- as.Date("2023-10-01") #Beginning of week 40 for 2023-2024 season
season22_start<-  as.Date("2022-07-01")
season23_start<- as.Date("2023-07-01")
season24_end<- as.Date("2024-04-30") #End of mandatory NHSN reporting period in 2024
```

# Load requisite data
This file is dependent on objects loaded from the `load_data.R` file, so if that hasn't been done yet, run that here.

```{r load-data}
source("load_data.R")
```


## Evaluate forecasts

### Score forecasts (MMWR Season)
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011393
```{r score-forecasts}

comb_fc<-read_parquet("data/raw_forecasts_MMWRseason.gz.parquet") %>% filter(forecast_date>season22_start_MMWR) %>% rename(observed=true_value, predicted=prediction, quantile_level=quantile) %>% drop_na(location)

get_duplicate_forecasts(comb_fc)

forecast_quantile <- comb_fc |>
  as_forecast_quantile()

print(forecast_quantile, 2)

prelim_scores<-score(forecast_quantile) |> add_relative_skill(compare= "model", by=c("location", "disease", "season"), baseline ="Baseline")

scores<- prelim_scores%>% summarise_scores(by=c("model", "target", "location", "season", "disease")) %>% 
  left_join(demog, by = "location") %>%
  left_join(hosp_capacity, by=c("location", "season")) %>%
  left_join(num_facilities, by=c("location", "season")) %>%
  left_join(seasonal_burden, by=c("location", "season", "disease")) %>%
  mutate(wis_per100k=wis/pop*100000, normalized_wis_dens=wis/density, wis_hosp_capacity= wis/inpatient_beds, wis_facilities=wis/median_facilities, wis_burden= wis/burden)

write_csv(scores, "results/forecast_scores_MMWR.csv")
```

### Score forecasts (July-June Season)
```{r score-summer-forecasts}

comb_fc_summer<-read_parquet("data/raw_forecasts.gz.parquet") %>% filter(forecast_date>season22_start) %>% rename(observed=true_value, predicted=prediction, quantile_level=quantile) %>% drop_na(location)  #alternative for July-June seasons

get_duplicate_forecasts(comb_fc_summer)

forecast_quantile_summer <- comb_fc_summer |>
  as_forecast_quantile() %>% arrange(forecast_date)

print(forecast_quantile_summer, 2)

prelim_scores_summer<-score(forecast_quantile_summer) |> add_relative_skill(compare= "model", by=c("location", "disease", "season"), baseline ="Baseline")

scores_summer<- prelim_scores_summer %>% summarise_scores(by=c("model", "target", "location", "season", "disease")) %>%  
  left_join(demog, by = "location") %>%
  left_join(hosp_capacity, by=c("location", "season")) %>%
  left_join(num_facilities, by=c("location", "season")) %>%
  left_join(seasonal_burden, by=c("location", "season", "disease")) %>%
  mutate(wis_per100k=wis/pop*100000, normalized_wis_dens=wis/density, wis_hosp_capacity= wis/inpatient_beds, wis_facilities=wis/median_facilities, wis_burden= wis/burden)


write_csv(scores_summer, "results/forecast_scores.csv") #alternative July-June season
```

## Combine forecast scores with forecastability scores

### MMWR Season
```{r combine-forecasts}
# scores<-read_csv("results/forecast_scores_MMWR.csv")

combo<- read.csv("results/combo_omega_MMWR.csv")
forecastability<-scores %>% left_join(combo %>% dplyr:: select(location, omega, season, disease), by= c("location", "season", "disease"))

write_csv(forecastability, "results/forecastability_results_MMWR.csv")
```

### July-June Season
```{r combine-forecasts-summer}
# scores_summer<-read_csv("results/forecast_scores.csv")
combo_summer<- read.csv("results/combo_omega.csv")
forecastability_summer<-scores_summer %>% left_join(combo_summer %>% dplyr:: select(location, omega, season, disease), by= c("location", "season", "disease"))
write_csv(forecastability_summer, "results/forecastability_results.csv")

```

